language: dart
sudo: false
dart:
  - stable
cache:
  directories:
    - $HOME/.pub-cache/hosted
script:
  - RUN_CHECKER=0 TEST_EXAMPLES=0 ./scripts/presubmit.sh
before_install:
  - . scripts/install_dependencies.sh
