name: scissors
version: 0.6.1
description: A CSS minifier / tree-shaker for AngularDart 1.x / Angular2.
authors:
- Olivier Chafik <ochafik@google.com>
homepage: http://github.com/google/dart-scissors
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  args: ">=0.12.0 <0.14.0"
  barback: ^0.15.0
  csslib: ">=0.12.0 <0.14.0"
  html: ^0.12.0
  intl: ">=0.8.0 <0.13.0"
  quiver: ^0.21.0
  source_maps: ^0.10.0
  path: ^1.3.0
dev_dependencies:
  dart_style: ^0.2.4
  transformer_test: ^0.2.0
  test: ^0.12.12
executables:
  scissors-inline-images: inline_images
  scissors-sassc: sassc_with_compass_functions
