name: scissors_angular1_example
version: 0.6.7
dependencies:
  angular: ">=1.1.2+2"
dev_dependencies:
  scissors: ^0.6.7
  dart_to_js_script_rewriter: ^0.1.0
  # template_cache_transformer: any
transformers:
# Use this transformer instead to force-build all the css files upfront:
# - scissors/eager_transformer
- scissors:
    verbose: true
    bidiCss: true
    cssJanusPath: ${PWD}/../../.dependencies/cssjanus/cssjanus.py
    release:
        imageInlining: inlineAllUrls
    # pruneCss: false
    # optimizeSvg: false
    # optimizePng: false
    compiledCssExtension: replace
    # sasscPath: path/to/sassc
    sasscArgs:
        - -I${PWD}/lib/some/sub
        - --load-path
        - lib/some/sub/directory
# This enables automatic reloader support in debug, and removal of
# reloader.dart import + calls in release.
- scissors/reloader/transformer
- angular:
    generate_template_cache: true
    entry_points:
        - web/main.dart
- $dart2js:
    # minify: false
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors
    # Uncomment to generate summaries from dart2js
    # - --dump-info
- dart_to_js_script_rewriter

# Do not use this line in your projects: this is just to use the enclosing
# version of Scissors:
dependency_overrides: {scissors: {path: ../..}}
